#!/bin/sh


#Setup the Sound Card
modprobe snd-bcm2835 


#bluetooth
sudo modprobe hci_uart
sleep 2
lsmod
hciattach /dev/ttyAMA0 bcm43xx 921600 noflow -
sleep 2
/usr/libexec/bluetooth/bluetoothd &
sleep 2
hciconfig hci0 up
sleep 2	


./../../Player/GPIO_cnfg.bash			&




DeviceUpdater=/Player/device_mounter.bash

start-stop-daemon -b --start --quiet --exec ${DeviceUpdater}


